### ISSUE TITLE
두번째

### ISSUE THREAD

**Issue by konghun** [roscore/Computing_Monitor#2]
Failed to convert CPU power to float. Setting it to 0.0
Traceback (most recent call last):
  File "/home/aimy/Computing_Monitor/test.py", line 86, in <module>
    cpu_instructions = get_cpu_instructions()
  File "/home/aimy/Computing_Monitor/test.py", line 48, in get_cpu_instructions
    return int(instructions.replace(',', ''))
ValueError: invalid literal for int() with base 10: ''

**Comment by roscore** [comment]
sensors | awk '/Package id 0:/ {print $4}' | cut -c 2-

위 명령어 실행 후 출력되는 로그 확인 부탁드립니다

**Comment by konghun** [comment]
aimy@aimy:~/Computing_Monitor$ sensors | awk '/Package id 0:/ {print $4}' | cut -c 2-
aimy@aimy:~/Computing_Monitor$ sensors | awk '/Package id 0:/ {print $4}' | cut -c 2-
aimy@aimy:~/Computing_Monitor$ sudo apt-get install lm-sensors
[sudo] password for aimy: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lm-sensors is already the newest version (1:3.6.0-7ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
aimy@aimy:~/Computing_Monitor$ sudo sensors | awk '/Package id 0:/ {print $4}' | cut -c 2-
aimy@aimy:~/Computing_Monitor$ ^C

**Comment by roscore** [comment]
perf stat -e instructions -a sleep 1 2>&1 | grep instructions | awk '{print $1}

위 명령어 실행 후 출력되는 로그 확인 부탁드립니다

**Comment by konghun** [comment]
aimy@aimy:~/Computing_Monitor$ perf stat -e instructions -a sleep 1 2>&1 | grep instructions | awk '{print $1}

> 
> 
> 
> 
>

**Comment by konghun** [comment]
aimy@aimy:~/Computing_Monitor$ perf stat -e instructions -a sleep 1 2>&1 | grep instructions | awk '{print $1}

> 
>
>

**Comment by konghun** [comment]
![image](https://github.com/roscore/Computing_Monitor/assets/127224626/ec0cff5c-e114-4221-8fab-57407a7ef657)
![Screenshot from 2024-05-27 11-40-15](https://github.com/roscore/Computing_Monitor/assets/127224626/48c4e2c2-09be-4a60-af48-58ad15529605)

**Comment by konghun** [comment]
Traceback (most recent call last):
  File "/home/aimy/Computing_Monitor/legacy.py", line 27, in <module>
    cpu_power = get_cpu_power()
  File "/home/aimy/Computing_Monitor/legacy.py", line 15, in get_cpu_power
    return float(cpu_power)
ValueError: could not convert string to float: b''

python3 legacy.py 
실행시 나오는 log입니다

**Comment by roscore** [comment]
```
sensors
```

위 명령어 실행 후 하기 출력과 비슷한 형태로 터미널 출력이 확인되시나요?

```
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +65.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +63.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +64.0°C  (high = +80.0°C, crit = +100.0°C)
```

**Comment by konghun** [comment]
![image](https://github.com/roscore/Computing_Monitor/assets/127224626/9df82d1a-c104-408b-9f10-9cd70d1918ee)

**Comment by roscore** [comment]
ls /sys/class/hwmon/
ls /sys/class/hwmon/hwmon*/device/

위 명령어를 사용하여 액세스 가능한 경로를 확인해주시겠습니까?

**Comment by konghun** [comment]
aimy@aimy:~$ ls /sys/class/hwmon/
hwmon0  hwmon1  hwmon2  hwmon3  hwmon4




aimy@aimy:~$ ls /sys/class/hwmon/hwmon*/device/
/sys/class/hwmon/hwmon0/device/:
address    dctype  firmware_rev  model      nvme0n1      rescan_controller  sqsize     subsystem
cntlid     dev     hwmon0        ng0n1      power        reset_controller   state      transport
cntrltype  device  kato          numa_node  queue_count  serial             subsysnqn  uevent

/sys/class/hwmon/hwmon1/device/:
ari_enabled               d3cold_allowed   enable       link           numa_node    resource          uevent
broken_parity_status      device           hwmon        local_cpulist  power        revision          vendor
class                     dma_mask_bits    iommu        local_cpus     power_state  subsystem
config                    driver           iommu_group  modalias       remove       subsystem_device
consistent_dma_mask_bits  driver_override  irq          msi_bus        rescan       subsystem_vendor

/sys/class/hwmon/hwmon2/device/:
cpufv  driver  driver_override  hwmon  input  modalias  power  subsystem  uevent

/sys/class/hwmon/hwmon3/device/:
cpufv  driver  driver_override  hwmon  input  modalias  power  subsystem  uevent

/sys/class/hwmon/hwmon4/device/:
apu_thermal_cap            hdcp_srm                 msi_bus                            product_number
ari_enabled                hwmon                    msi_irqs                           remove
boot_vga                   i2c-10                   numa_node                          rescan
broken_parity_status       i2c-9                    pcie_replay_count                  reset
class                      iommu                    power                              reset_method
config                     iommu_group              power_dpm_force_performance_level  resource
consistent_dma_mask_bits   ip_discovery             power_dpm_state                    resource0
consumer:pci:0000:0c:00.1  irq                      power_state                        resource0_wc
current_link_speed         link                     pp_cur_state                       resource2
current_link_width         local_cpulist            pp_dpm_dcefclk                     resource2_wc
d3cold_allowed             local_cpus               pp_dpm_fclk                        resource4
device                     max_link_speed           pp_dpm_mclk                        resource5
dma_mask_bits              max_link_width           pp_dpm_pcie                        revision
driver                     mem_info_gtt_total       pp_dpm_sclk                        serial_number
driver_override            mem_info_gtt_used        pp_dpm_socclk                      subsystem
drm                        mem_info_preempt_used    pp_force_state                     subsystem_device
enable                     mem_info_vis_vram_total  pp_mclk_od                         subsystem_vendor
firmware_node              mem_info_vis_vram_used   pp_num_states                      thermal_throttling_logging
fw_version                 mem_info_vram_total      pp_od_clk_voltage                  uevent
gpu_busy_percent           mem_info_vram_used       pp_sclk_od                         vbios_version
gpu_metrics                mem_info_vram_vendor     pp_table                           vendor
graphics                   modalias                 product_name

**Comment by konghun** [comment]
alias aimy='ssh -X aimy@192.168.50.110'


에이미 아이피입니다!

**Comment by konghun** [comment]
aimy@aimy:~$ sudo powertop --csv=powertop_report.txt tikme=10s
modprobe cpufreq_stats failedCannot load from file /var/cache/powertop/saved_results.powertop
Cannot load from file /var/cache/powertop/saved_parameters.powertop
File will be loaded after taking minimum number of measurement(s) with battery only 
RAPL device for cpu 0
RAPL Using PowerCap Sysfs : Domain Mask 5
RAPL device for cpu 0
RAPL Using PowerCap Sysfs : Domain Mask 5
Devfreq not enabled
glob returned GLOB_ABORTED
Cannot load from file /var/cache/powertop/saved_parameters.powertop
File will be loaded after taking minimum number of measurement(s) with battery only 
Preparing to take measurements
Segmentation fault


sudo powertop --csv=powertop_report.txt time=10s
powercap 에러




aimy@aimy:~$ sudo modprobe cpufreq_stats
[sudo] password for aimy: 
modprobe: FATAL: Module cpufreq_stats not found in directory /lib/modules/6.5.0-35-generic


cpu freq_state 에러

**Comment by roscore** [comment]
ubuntu 22.04 에서 실행시킬 수 있도록 코드를 수정했습니다. 감사합니다.
